"""Patch ORM model.

Stores each patch attempt (unified diff) generated by the agent,
along with its test results. This gives a full audit trail of
every iteration the agent tried.
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class Patch(Base):
    """A single patch attempt within an agent run."""

    __tablename__ = "patches"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False
    )
    diff: Mapped[str] = mapped_column(Text, nullable=False)
    test_result: Mapped[str | None] = mapped_column(Text, nullable=True)
    test_passed: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    iteration_number: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Relationships
    run: Mapped["Run"] = relationship("Run", back_populates="patches")  # noqa: F821

    def __repr__(self) -> str:
        return f"<Patch run={self.run_id} iter={self.iteration_number} passed={self.test_passed}>"
